package ru.sirius.account.ui.goods;


import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.swing.SwingValidationGroup;
import ru.sirius.account.model.entity.Category;


public class CreateCategoryPanel extends javax.swing.JPanel {

    
    private Category category = new Category();
    private final SwingValidationGroup validationGroup = SwingValidationGroup.create();

    
    /**
     * Creates new form CreateGroupPanel
     */
    public CreateCategoryPanel() {
                
        initComponents();                            
        validationGroup.add(groupNameTextField, StringValidators.REQUIRE_NON_EMPTY_STRING);
    }

    public SwingValidationGroup getValidationGroup() {
        return validationGroup;
    }
    
    
    public Category getCategory(){         
        category.setName(groupNameTextField.getText());
        return category;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        groupNameTextField.setName("Наименование"); // NOI18N

        jLabel3.setText("Наименование");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField groupNameTextField;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
